# Generated by Django 4.0.1 on 2022-04-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('faculty', models.CharField(max_length=100)),
                ('team', models.IntegerField()),
                ('apply', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
