# Generated by Django 4.0.1 on 2022-04-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_faculty_teacher_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='apply',
        ),
        migrations.AddField(
            model_name='project',
            name='acceptedstudents',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='appliedstudents',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
