# Generated by Django 4.0.1 on 2022-04-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_apply_project_acceptedstudents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='acceptedstudents',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='appliedstudents',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
